import type { Producto } from "@/types/producto"

// Datos de demostración para usar cuando no hay conexión a la base de datos
export const demoProductos: Producto[] = [
  {
    id: 1,
    nombre: "Guantes de látex",
    descripcion: "Guantes desechables para procedimientos",
    categoria: "Insumos",
    precio: 5000,
    stock: 150,
    stock_minimo: 50,
    ubicacion: "Almacén principal",
    fecha_vencimiento: new Date(new Date().setMonth(new Date().getMonth() + 6)).toISOString(),
    requiere_refrigeracion: false,
    proveedor: "Medical Supplies Inc.",
    codigo: "GL-001",
    unidad_medida: "Caja",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    nombre: "Anestesia local",
    descripcion: "Anestesia para procedimientos dentales",
    categoria: "Medicamentos",
    precio: 12000,
    stock: 20,
    stock_minimo: 30,
    ubicacion: "Refrigerador",
    fecha_vencimiento: new Date(new Date().setMonth(new Date().getMonth() + 2)).toISOString(),
    requiere_refrigeracion: true,
    proveedor: "Pharma Solutions",
    codigo: "AN-002",
    unidad_medida: "Ampolla",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    nombre: "Resina compuesta",
    descripcion: "Material para restauraciones dentales",
    categoria: "Materiales",
    precio: 35000,
    stock: 45,
    stock_minimo: 20,
    ubicacion: "Gabinete 2",
    fecha_vencimiento: new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toISOString(),
    requiere_refrigeracion: false,
    proveedor: "Dental Materials Co.",
    codigo: "RC-003",
    unidad_medida: "Jeringa",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    nombre: "Mascarillas quirúrgicas",
    descripcion: "Mascarillas desechables de 3 capas",
    categoria: "Insumos",
    precio: 3000,
    stock: 10,
    stock_minimo: 100,
    ubicacion: "Almacén principal",
    fecha_vencimiento: new Date(new Date().setMonth(new Date().getMonth() + 12)).toISOString(),
    requiere_refrigeracion: false,
    proveedor: "Medical Supplies Inc.",
    codigo: "MQ-004",
    unidad_medida: "Caja",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    nombre: "Radiografías dentales",
    descripcion: "Placas para radiografías intraorales",
    categoria: "Diagnóstico",
    precio: 25000,
    stock: 200,
    stock_minimo: 50,
    ubicacion: "Sala de rayos X",
    fecha_vencimiento: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    requiere_refrigeracion: false,
    proveedor: "Imaging Solutions",
    codigo: "RD-005",
    unidad_medida: "Paquete",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
